name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    env:
        RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          #- nightly # broken as of 2023-07-11

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - uses: rui314/setup-mold@v1

      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt --all --check

      - run: cargo clippy --all --all-features -- -D warnings

      - run: cargo test --workspace --verbose

      - uses: bnjbvr/cargo-machete@main
